import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample dataset
data = {
    "Address": [
        "SHOP NO 18 SHYAMKAMAL C AGARWARL MARKET NEAR SAHAKARI BAHNDAR VILE PARLE EAST",
        "SHOP NO 24 B WING SHYAMKAMAL CHS LTD AGARWAL MARKET MONGHIAI ROAD VILE PARLE EAST",
        "CO B G MEDICAL R N 18 FIRST FLOOR MARATHA MANDIRS BABASAHEB GAWDE HOSPITAL M G ROAD",
        "SHOP NO 19 D WING SHYAM KAMAL CO OP HOS SOC LTD AGARWAL MARKET VILEPARLE EAST OPP SAHAKARI BHANDAR",
        "SHOP NO 97 MUNICIPAL MARKET BELOW DINANATH MANGESHKAR HALL TEJPAL ROAD VILE PARLE EAST",
        "4 GALAXY ARCADE 52 M G ROAD VILEPARLE EAST",
        "SHOP NO 5 GALAXY ARCADE 52 M G ROAD VILEPARLE EAST",
        "SHOP NO 5 GR FLR ANAND BLDG ARUNESHWAR CHS LTD PLOT NO 225 226 OPP SHIV SAGAR HOTEL SHRIDDANAND RD VILE PARLE E",
        "23 C SHYAM KAMAL BUILDING AGARWAL MARKET BEHIND DINANATH MANGESHKAR HALL VILEPARLE EAST",
        "NAND PREM SHOPPING CENTRE NEHRU ROAD VILE PARLE EAST NEHRU ROAD VILE PARLE EAST",
        "1 NAND PREM SHOPPING CENTRE NEHRU RD VILE PARLE E",
        "SHOP NO 5 A AND 5B GROUND FLOOR KRISHNA COTTAGE BUILDING HANUMAN ROAD VILEPARLE EAST",
        "SHOP NO 5 A AND 5B GROUND FLOOR KRISHNA COTTAGE BUILDING HANUMAN ROAD VILEPARLE EAST",
        "SHOP NO 5 A AND 5B GROUND FLOOR KRISHNA COTTAGE BUILDING HANUMAN ROAD VILEPARLE EAST",
        "SHOP NO 5 A AND 5B GROUND FLOOR KRISHNA COTTAGE BUILDING HANUMAN ROAD VILEPARLE EAST",
        "SHOP NO 7 GROUND FLOOR OM SAI NIWAS CHSL SUBHASH RD OPP RAM MANDIR VILEPARLE EAST",
        "6 TWINKLE APARTMENT OPP KAMAT CLUB LOKHANDWALA ANDHERI WEST MUMBAIMUMBAI MAHARASHTRA",
        "9 GR FLOOR SNEHA BLDG B WING APNA GHARUNIT NO 11 CHS LTD LOKHANDWALA COMPLEX ANDHARI WEST",
        "9 GR FLOOR SNEHA BLDG B WING APNA GHARUNIT NO 11 CHS LTD LOKHANDWALA COMPLEX ANDHARI WEST",
        "A WING 101 CRYSTAL PLAZA ground floor new LINK ROADopp infinity mall Andheri West",
        "A WING 101 CRYSTAL PLAZA ground floor new LINK ROADopp infinity mall Andheri West",
        "GROUND FLOOR SHOP NO 1 AND 2 PARUL CO OPHOUSING SOCIETY LTD  VEERA DESAI ROSD ANDHERI WEST",
        "GROUND FLOOR SHOP NO 1 AND 2 PARUL CO OPHOUSING SOCIETY LTD  VEERA DESAI ROSD ANDHERI WEST",
        "GROUND FLOOR SHOP NO 1 AND 2 PARUL CO OPHOUSING SOCIETY LTD  VEERA DESAI ROSD ANDHERI WEST",
        "23 C SHYAM KAMAL BUILDING AGARWAL MARKET BEHIND DINANATH MANGESHKAR HALL VILEPARLE EAST"

    ]
}

df = pd.DataFrame(data)

# Extract distinct keywords
def extract_keywords(addresses):
    vectorizer = TfidfVectorizer(stop_words='english')
    vectorizer.fit_transform(addresses)
    return sorted(set(vectorizer.get_feature_names_out()))

keywords = extract_keywords(df["Address"])
print("Distinct Keywords:", keywords)

# Function to search for related addresses
def search_addresses(df, query):
    query = query.lower()
    return df[df["Address"].str.lower().str.contains(query, na=False)]

# Example search
query = input("Enter a keyword to search for related addresses: ")
result = search_addresses(df, query)

print("\nRelated Addresses:")
print(result)
